### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by david-soloveichik** [DNA-and-Natural-Algorithms-Group/peppercompiler#2]
There is a typo in the README.md file where `pepper-compile` should be `pepper-compiler`. Also it would be great to include documentation on the system and component files there.

**Comment by cgevans** [comment]
(Apparently, Github automatically closes issues based on parsing of commit messages.)

The typo should now be fixed, and some documentation on system and component files is now in doc/; it still should be more discoverable, however.
